// <auto-generated />
using System;
using EntityDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cms.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190602073617_test1")]
    partial class test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Base.City", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Model.Base.Good", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("Model.Base.Location", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("Address");

                    b.Property<decimal?>("CityId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("Code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .IsUnicode(false)
                        .HasDefaultValue("shop");

                    b.Property<string>("Name");

                    b.Property<string>("Tell");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("Model.sal.FactorDoc", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("Code");

                    b.Property<DateTime>("Confrimdate");

                    b.Property<string>("Date");

                    b.Property<decimal?>("LocationId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("FactorDocs");
                });

            modelBuilder.Entity("Model.sal.FactorDocDetail", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("AddressBuy");

                    b.Property<decimal?>("GoodsId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<decimal?>("FactorDocId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<float>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.HasIndex("FactorDocId");

                    b.ToTable("FactorDocDetails");
                });

            modelBuilder.Entity("Model.Base.Location", b =>
                {
                    b.HasOne("Model.Base.City")
                        .WithMany("LocatioId")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("Model.sal.FactorDoc", b =>
                {
                    b.HasOne("Model.Base.Location")
                        .WithMany("LocationId")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("Model.sal.FactorDocDetail", b =>
                {
                    b.HasOne("Model.Base.Good", "Goods")
                        .WithMany("GoodId")
                        .HasForeignKey("GoodsId");

                    b.HasOne("Model.sal.FactorDoc")
                        .WithMany("FactorDocId")
                        .HasForeignKey("FactorDocId");
                });
#pragma warning restore 612, 618
        }
    }
}
